### ISSUE TITLE
Publishing zarafa-base image dockerfile

### ISSUE THREAD

**Issue by luclu** [LECKERBEEFde/docker-zarafa#1]
Are there any plans to publish the recipe for the base-image?
I would really appreciate it! :heart:

**Comment by LECKERBEEFde** [comment]
Hello lucli,

the zarafabase image wasn't built with a dockerfile. It's a ubuntu image and the zarafa dependencies + server were manually installed and afterwards uploaded to docker-hub.

**Comment by LECKERBEEFde** [comment]
@luclu https://github.com/LECKERBEEFde/docker-zarafa-base
